spring:
  datasource:
    url: jdbc:postgresql:///${DB_NAME}?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=${INSTANCE_CONNECTION_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  datasource.hikari:
    maximumPoolSize: 10
    minimumIdle: 1
    idleTimeout: 60000
    connectionTimeout: 30000